[server]
# Enable network access from other devices
address = "0.0.0.0"
port = 8501

# Disable CORS protection for local network access
enableCORS = false
enableXsrfProtection = false

[browser]
# Disable auto-opening browser on server start
gatherUsageStats = false

[theme]
# Codrivity brand colors
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
# Development settings
developmentMode = false 